version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pokedex_db
    restart: always
    environment:
      POSTGRES_USER: usuario_poke
      POSTGRES_PASSWORD: senha_secreta_poke
      POSTGRES_DB: pokedex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: pokedex_api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://usuario_poke:senha_secreta_poke@db:5432/pokedex_db

volumes:
  postgres_data:
